apiVersion: 1

datasources:
  - name: LibreNMS DB
    uid: librenms-db
    type: mysql
    access: proxy
    url: $LIBRENMS_DB_HOST
    user: $LIBRENMS_DB_USER
    isDefault: true
    editable: false
    jsonData:
      database: $LIBRENMS_DB_NAME
      maxOpenConns: 5
      maxIdleConns: 2
    secureJsonData:
      password: $__file{/run/secrets/librenms_db_password}

  - name: Mist Prometheus
    uid: mist-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
    jsonData:
      timeInterval: 30s
