services:
  keep-backend:
    environment:
      KEEP_WORKFLOWS_DIRECTORY: /config/workflows
      KEEP_PROVIDERS_DIRECTORY: /config/providers
    volumes:
      - /opt/stacks/keep-config/keep/workflows:/config/workflows:ro
      - /opt/stacks/keep/provider-config:/config/providers:ro
